/**
 * Mock supplier data for the POS Suppliers module.
 * Replace with API when backend is ready.
 */

export const SUPPLIER_CATEGORIES = [
  'Vegetables',
  'Meat',
  'Seafood',
  'Groceries',
  'Spices',
  'Dairy',
  'Oils',
  'Packaging',
]

export const MOCK_SUPPLIERS = [
  {
    id: 1,
    name: 'Perera Groceries',
    phone: '077 234 5678',
    email: 'perera.groceries@example.com',
    address: '45 Station Rd, Matara',
    category: 'Groceries',
    totalPurchases: 185000,
    payableAmount: 42000,
  },
  {
    id: 2,
    name: 'Sena Poultry',
    phone: '071 876 5432',
    email: 'orders@senapoultry.lk',
    address: '12 Industrial Zone, Galle',
    category: 'Meat',
    totalPurchases: 320000,
    payableAmount: 85000,
  },
  {
    id: 3,
    name: 'Green Valley Farms',
    phone: '076 112 3344',
    email: '',
    address: '88 Farm Lane, Hakmana',
    category: 'Vegetables',
    totalPurchases: 96000,
    payableAmount: 0,
  },
  {
    id: 4,
    name: 'Ceylon Spice Traders',
    phone: '075 998 2211',
    email: 'sales@ceylonspice.lk',
    address: '3 Spice Market, Kandy',
    category: 'Spices',
    totalPurchases: 142000,
    payableAmount: 18500,
  },
  {
    id: 5,
    name: 'Ocean Fresh Seafood',
    phone: '070 445 6677',
    email: 'oceanfresh@example.com',
    address: 'Harbour Rd, Beruwala',
    category: 'Seafood',
    totalPurchases: 275000,
    payableAmount: 62000,
  },
  {
    id: 6,
    name: 'Lanka Dairy Co-op',
    phone: '078 223 9900',
    email: 'supply@lankadairy.lk',
    address: '22 Dairy Complex, Nuwara Eliya',
    category: 'Dairy',
    totalPurchases: 118000,
    payableAmount: 0,
  },
  {
    id: 7,
    name: 'Golden Oil Distributors',
    phone: '077 556 7788',
    email: '',
    address: '7 Warehouse St, Colombo 14',
    category: 'Oils',
    totalPurchases: 89000,
    payableAmount: 12000,
  },
  {
    id: 8,
    name: 'PackRight Solutions',
    phone: '071 334 5566',
    email: 'info@packright.lk',
    address: '19 Export Park, Katunayake',
    category: 'Packaging',
    totalPurchases: 54000,
    payableAmount: 0,
  },
  {
    id: 9,
    name: 'Nimal Fresh Produce',
    phone: '076 667 8899',
    email: 'nimal@freshproduce.lk',
    address: '5 Market Square, Matara',
    category: 'Vegetables',
    totalPurchases: 203000,
    payableAmount: 34000,
  },
  {
    id: 10,
    name: 'Metro Meat Wholesale',
    phone: '070 112 4455',
    email: 'accounts@metromeat.lk',
    address: '60 Wholesale Ave, Kurunegala',
    category: 'Meat',
    totalPurchases: 410000,
    payableAmount: 95000,
  },
]
