/**
 * ThermalReceipt.jsx
 *
 * Prints an 80mm thermal-paper-style receipt by opening a dedicated print
 * window with a fully self-contained HTML document.
 *
 * The document markup + CSS are generated by the SHARED receipt template
 * (./receiptTemplate) — the exact same markup the on-screen ReceiptModal
 * preview renders — so the preview and the printed output always match 1:1.
 *
 * Usage:
 *   import { printThermalReceipt } from './ThermalReceipt'
 *   import { buildReceiptData } from './receiptTemplate'
 *
 *   const receipt = buildReceiptData(order, { settings, authUser })
 *   await printThermalReceipt(receipt)
 *
 * Returns a Promise that resolves when the print dialog closes (or rejects
 * if the popup is blocked).
 */
import { buildReceiptData, buildReceiptHTML } from './receiptTemplate'

/**
 * Opens a print window with the thermal receipt and triggers the browser
 * print dialog.
 *
 * @param {object} receiptData - pre-built receipt from buildReceiptData()
 *                               OR a raw order/invoice object
 * @param {object} opts        - { settings, authUser } used only when a raw
 *                               order is passed in
 * @returns {Promise<void>}
 */
export function printThermalReceipt(receiptData, opts = {}) {
  return new Promise((resolve) => {
    const receipt = receiptData && receiptData.hotelName
      ? receiptData
      : buildReceiptData(receiptData, opts)

    const html = buildReceiptHTML(receipt)

    // Screen එකට නොපෙනෙන hidden iframe එකක් සාදයි
    const iframe = document.createElement('iframe')
    iframe.style.position = 'fixed'
    iframe.style.right = '0'
    iframe.style.bottom = '0'
    iframe.style.width = '0'
    iframe.style.height = '0'
    iframe.style.border = '0'
    document.body.appendChild(iframe)

    const doc = iframe.contentWindow.document
    doc.open()
    doc.write(html)
    doc.close()

    iframe.onload = () => {
      setTimeout(() => {
        iframe.contentWindow.focus()
        iframe.contentWindow.print()

        const cleanup = () => {
          if (document.body.contains(iframe)) {
            document.body.removeChild(iframe)
          }
          resolve()
        }

        if ('onafterprint' in iframe.contentWindow) {
          iframe.contentWindow.onafterprint = cleanup
          setTimeout(cleanup, 20000)
        } else {
          setTimeout(cleanup, 1000)
        }
      }, 300)
    }
  })
}

export default printThermalReceipt