/**
 * ThermalReceipt.jsx
 *
 * Prints an 80mm thermal-paper-style receipt by opening a dedicated print
 * window with a fully self-contained HTML document.
 *
 * The document markup + CSS are generated by the SHARED receipt template
 * (./receiptTemplate) — the exact same markup the on-screen ReceiptModal
 * preview renders — so the preview and the printed output always match 1:1.
 *
 * Usage:
 *   import { printThermalReceipt } from './ThermalReceipt'
 *   import { buildReceiptData } from './receiptTemplate'
 *
 *   const receipt = buildReceiptData(order, { settings, authUser })
 *   await printThermalReceipt(receipt)
 *
 * Returns a Promise that resolves when the print dialog closes (or rejects
 * if the popup is blocked).
 */
import { buildReceiptData, buildReceiptHTML } from './receiptTemplate'

/**
 * Opens a print window with the thermal receipt and triggers the browser
 * print dialog.
 *
 * @param {object} receiptData - pre-built receipt from buildReceiptData()
 *                               OR a raw order/invoice object
 * @param {object} opts        - { settings, authUser } used only when a raw
 *                               order is passed in
 * @returns {Promise<void>}
 */
export function printThermalReceipt(receiptData, opts = {}) {
  return new Promise((resolve, reject) => {
    // Accept either a pre-built receipt payload or a raw order object.
    const receipt = receiptData && receiptData.hotelName
      ? receiptData
      : buildReceiptData(receiptData, opts)

    // Open a small popup window sized for an 80mm receipt preview
    const win = window.open(
      '',
      '_blank',
      'width=340,height=600,menubar=no,toolbar=no,location=no,status=no,scrollbars=yes'
    )

    if (!win) {
      reject(new Error('Popup blocked. Please allow popups for this site.'))
      return
    }

    const html = buildReceiptHTML(receipt)
    win.document.open()
    win.document.write(html)
    win.document.close()

    // Wait for resources (logo image) to load, then print
    win.onload = () => {
      // Small delay ensures fonts/layout are fully rendered
      setTimeout(() => {
        win.focus()
        win.print()

        // Resolve after print dialog closes (afterprint fires on most browsers)
        const cleanup = () => {
          resolve()
          win.close()
        }

        if ('onafterprint' in win) {
          win.onafterprint = cleanup
          // Fallback timeout in case onafterprint doesn't fire
          setTimeout(cleanup, 30_000)
        } else {
          // Safari fallback
          setTimeout(cleanup, 1_000)
        }
      }, 250)
    }
  })
}

export default printThermalReceipt
